blank_issues_enabled: false
contact_links:
  - name: (Sample) Feature request
    url: https://github.com/masutakanet/sandbox2/discussions/categories/ideas
    about: Share ideas for new features
  - name: (Sample) Ask a question
    url: https://github.com/masutakanet/sandbox2/discussions/categories/q-a
    about: Ask questions and discuss with other community members
